# Governing Equations of Electrodynamics

Fluid Dynamics are written with Volumetric Equations, and thus to incorporate Electrodynamics in them, we have to write Electrodynamics Equations also in a Volumetric formulation. This page should serve as a review of the nessecary Electrodynamics, while also deriving theese volumetric formulations nessecary for Magnetohydrodynamics.

The below notes were made with reference to An Introduction to Magnetohydrodynamics by PA Davidson.[@Davidson_2001]

## Lorentz Force

A charged particle with velocity $v$ and charge $q$ experiences the force given by

\begin{equation}
f = q \vec{E_s} + q \vec{E_i} + q (\vec{v} \times \vec{B})
\end{equation}

where:

\begin{itemize}
    \item $\vec{E_s}$ = Static Electric Field
    \item $\vec{E_i}$ = Force from Varying Magnetic Field
    \item $q(\vec{v} \times \vec{B})$ = Lorentz Force
\end{itemize}

The static electric field is irrotational and has a fixed divergence:

\begin{equation}
\nabla \times \vec{E_s} = 0
\end{equation}

\begin{equation}
\nabla \cdot \vec{E_s} = \frac{\rho_e}{\epsilon_0}
\end{equation}

where:

\begin{itemize}
    \item $\rho_e$ = Total Charge Density
    \item $\epsilon_0$ = Permittivity of Free Space
\end{itemize}


The Electrostatic Potential $V$ is given by:

\begin{equation}
\vec{E_s} = - \nabla V
\end{equation}

\begin{equation}
\nabla^2 V = \frac{\rho_e}{\epsilon_0}
\end{equation}

The total electric field given by $\vec{E_s} + \vec{E_i} = \vec{E}$ is subject to the following constraints:

\begin{equation}
\nabla \cdot \vec{E} = \frac{\rho_e}{\epsilon_0} \quad \text{(Gauss's Law)}
\end{equation}

\begin{equation}
\nabla \times \vec{E} = \frac{\partial \vec{B}}{\partial t} \quad \text{(Faraday's Law)}
\end{equation}

The magnetic field $\vec B$ is a pseudovector, which will have consequences for Dynamo Theory.

### Volumetric Lorentz Force

Let $\vec J$ represent current density.

\begin{equation}\vec J = \sigma \vec E\end{equation}
In a moving frame, the same equation can be written as 
\begin{equation}\vec J= \sigma (\vec E + \vec v \times \vec B)\end{equation}
We can identify this as the Volumetric Gauss Law

The Electrostatic Lorentz force is given by 

$\vec F = q (\vec E + \vec v \times B)$

Dividing this by the volume, we get 

\begin{equation}\vec f = \rho_l \vec E + \vec J \times B\end{equation}
This is the volumetric Lorentz Force Equation.

> **Claim**: In non Relativistic Frames, the leading $\rho_l \vec E$ term is negligible. 
> 
> **Proof**: 
> We can write the continuity equation of charge to be of the form
> $$\nabla \cdot \vec J = - \frac{\partial \rho _l}{\partial t}$$
> This simply says that the rate at which charge is decreasing inside a small volume must equal the rate at which charge flows out across the surface of that volume. 
> Taking divergence on both sides of the volumetric gauss law, and substituting it in the continuity of charge equation, we get
> $$\frac{\partial \rho _l}{\partial t} + \frac{\rho _l}{\tau _ l} + \sigma \nabla \cdot (\vec v \times \vec B) = 0$$
> where $\tau_l$ represents the relaxation time of the system and is a very small quantity.
> So when we observe at timescales much larger than $\tau _l$,
> $$\frac{\partial \rho_l}{\partial t} << \frac{\rho _l}{\tau _ l} $$
> and we can neglect the term $\frac{\partial \rho_l}{\partial t}$.Rearranging the terms we get that
> $\rho_l = - \epsilon _ 0 \tau _l \nabla \cdot ((\vec v \times \vec B)$ is very small and can be neglected as well (because $\tau _l$ is small)
> Going back to the volumetric Lorentz Force equation, we find under these assumptions of Non-Relativistic frames, the equation reduces to 
> \begin{equation}\vec f = \vec J \times \vec B\end{equation}

## Ampere Maxwell's Laws

The Ampere Maxwell Law is given by 
\begin{equation}
\nabla \times \vec B = \mu \left[ \vec J + \epsilon _ 0 \frac{\partial \vec E}{\partial t} \right]
\end{equation}
In conductors, this second term $\epsilon _ 0 \frac{\partial \vec E}{\partial t}$ contributes negligibly, and Maxwell's Correction is not nessecary, leaving us with $\nabla \times B = \mu \vec J$

Inverting the last equation there gives us the biot savart law.

\begin{equation}
B(x) = \frac {\mu}{4 \pi} \int \frac{J(x') \times \vec r}{r^3} d^3 x' 
\end{equation}

## Reduced Maxwell's Laws 

We try to write the Maxwell's laws in a form friendly to Magnetohydrodynamics.

The general form of Maxwell's Laws are given by the following:

\begin{align}
\nabla \cdot \vec{E} &= \frac{\rho_l}{\epsilon_0} \\
\nabla \times \vec{E} &= - \frac{\partial \vec{B}}{\partial t} \\
\nabla \cdot \vec{B} &= 0 \\
\nabla \times \vec{B} &= \mu \left( \vec{J} + \epsilon_0 \frac{\partial \vec{E}}{\partial t} \right)
\end{align}

In addition to the Maxwell's Relations the followign relations as well: 

\begin{equation}\nabla \cdot \vec J = - \frac {\partial \rho _ l}{\partial t} \\ \vec F = q (\vec E + \vec v \times \vec B)\end{equation}

For MHD, $\rho_l$ is negligible and the displacement currents are negligible, which gives us the following relations which are applicable in case of MHD.

\begin{align}
\nabla \times \vec B =\mu \vec J \\ 
\nabla \cdot \vec J = 0 \\ 
\nabla \times \vec E = - \frac{\partial \vec B}{\partial t} \\ 
\nabla \cdot \vec B = 0 \\  
\vec J= \sigma (\vec E + \vec v \times \vec B) \\ 
\vec F = \vec J \times \vec B
\end{align}

